services:
  ambev_developerevaluation_webapi:
    image: ${DOCKER_REGISTRY-}ambevdeveloperevaluationwebapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Host=ambev_developer_evaluation_database;Port=5434;Database=developer_evaluation;Username=developer;Password=ev@luAt10n
      - MongoDbSettings__ConnectionString=mongodb://developer:ev4luAt10n@ambev_developer_evaluation_nosql:27017
      - MongoDbSettings__DatabaseName=DeveloperEvaluation
      - MongoDbSettings__CollectionName=Sales
      - RabbitMqSettings__ConnectionString=amqp://developer:ev4luAt10n@ambev_developer_evaluation_queue:5673
      - RabbitMqSettings__QueueName=Worker-Sales
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ambev_developerevaluation_database
      - ambev_developerevaluation_nosql
      - ambev_developerevaluation_queue
      - ambev_developerevaluation_worker
    networks:
      - ambev_network

  ambev_developerevaluation_worker:
    image: ${DOCKER_REGISTRY-}ambevdeveloperevaluationworker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=ambev_developer_evaluation_database;Port=5434;Database=developer_evaluation;Username=developer;Password=ev@luAt10n
      - MongoDbSettings__ConnectionString=mongodb://developer:ev4luAt10n@ambev_developer_evaluation_nosql:27017
      - MongoDbSettings__DatabaseName=DeveloperEvaluation
      - MongoDbSettings__CollectionName=Sales
      - RabbitMqSettings__ConnectionString=amqp://developer:ev4luAt10n@ambev_developer_evaluation_queue:5673
      - RabbitMqSettings__QueueName=Worker-Sales
    depends_on:
      - ambev_developerevaluation_database
      - ambev_developerevaluation_nosql
      - ambev_developerevaluation_queue
    networks:
      - ambev_network

  ambev_developerevaluation_database:
    image: postgres:13
    environment:
      POSTGRES_DB: developer_evaluation
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: ev@luAt10n
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ambev_network

  ambev_developerevaluation_nosql:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: ev4luAt10n
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ambev_network

  ambev_developerevaluation_queue:
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_USER: developer
      RABBITMQ_DEFAULT_PASS: ev4luAt10n
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ambev_network

volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data:

networks:
  ambev_network:
    driver: bridge
