services:
  ambev_developerevaluation_webapi:
    build:
      context: .
      dockerfile: src/Ambev.DeveloperEvaluation.WebApi/Dockerfile
    image: ambevdeveloperevaluationwebapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=ambev_developerevaluation_database;Port=5432;Database=developer_evaluation;Username=developer;Password=ev@luAt10n
      - MongoDbSettings__ConnectionString=mongodb://developer:ev4luAt10n@ambev_developerevaluation_nosql:27017
      - MongoDbSettings__DatabaseName=DeveloperEvaluation
      - MongoDbSettings__CollectionName=Sales
      - RabbitMqSettings__ConnectionString=amqp://developer:ev4luAt10n@ambev_developerevaluation_queue:5672
      - RabbitMqSettings__QueueName=Worker-Sales
    ports:
      - "8080:8080"    
    depends_on:
      ambev_developerevaluation_database:
        condition: service_healthy
      ambev_developerevaluation_queue:
        condition: service_healthy
      ambev_developerevaluation_nosql:
        condition: service_healthy
    tty: true

  ambev_developerevaluation_database:
    image: postgres:13
    environment:
      POSTGRES_DB: developer_evaluation
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: ev@luAt10n
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U developer -d developer_evaluation"]
      interval: 10s
      timeout: 5s
      retries: 5

  ambev_developerevaluation_nosql:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: ev4luAt10n
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  ambev_developerevaluation_queue:
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_USER: developer
      RABBITMQ_DEFAULT_PASS: ev4luAt10n
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data:
